SalinoMvc5/Areas/Admin/Controllers/Offers/OfferPricesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Salino.DataLayer;
using Salino.Models;

namespace SalinoMvc5.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin1")]
    public class OfferPricesController : Controller
    {
        private SalinoContext db = new SalinoContext();

        // GET: Admin/OfferPrices
        public ActionResult Index()
        {
            var result = db.OfferPrices.Where(x => x.AsNumber != 0 ).ToList();
            return View(result);
        }

        // GET: Admin/OfferPrices/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OfferPrice offerPrice = db.OfferPrices.Find(id);
            if (offerPrice == null)
            {
                return HttpNotFound();
            }
            return View(offerPrice);
        }

        // GET: Admin/OfferPrices/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/OfferPrices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( OfferPrice offerPrice)
        {
            if (ModelState.IsValid)
            {
                db.OfferPrices.Add(offerPrice);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(offerPrice);
        }

        // GET: Admin/OfferPrices/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OfferPrice offerPrice = db.OfferPrices.Find(id);
            if (offerPrice == null)
            {
                return HttpNotFound();
            }
            return View(offerPrice);
        }

        // POST: Admin/OfferPrices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( OfferPrice offerPrice)
        {
            if (ModelState.IsValid)
            {
                db.Entry(offerPrice).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(offerPrice);
        }

        // GET: Admin/OfferPrices/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OfferPrice offerPrice = db.OfferPrices.Find(id);
            if (offerPrice == null)
            {
                return HttpNotFound();
            }
            return View(offerPrice);
        }

        // POST: Admin/OfferPrices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OfferPrice offerPrice = db.OfferPrices.Find(id);
            db.OfferPrices.Remove(offerPrice);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SalinoMvc5/Areas/Admin/Views/OfferPrices/Create.cshtml
@model Salino.Models.OfferPrice

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<section class="content-header">
    <h1 style="margin-bottom:15px">
        تخفیف چندمی به بعد

    </h1>
    <ol class="breadcrumb">
        <li><a href="/Admin/Default/Index"><i class="fa fa-dashboard"></i> مدیریت</a></li>
        <li class="active"><a href="/Admin/OfferPrices/Index">       تخفیف چندمی به بعد</a></li>
        <li class="active">   تخفیف جدید </li>
    </ol>
</section>
<div class="box box-info container">


    @using (Html.BeginForm("Create", "OfferPrices"))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>               تخفیف چندمی به بعد</h4>

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AsNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AsNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AsNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <hr />


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">

                    <button class="btn btn-social btn-success" type="submit">
                        <i class="fa fa-save"></i> ذخیره
                    </button>
                    <a class="btn btn-social btn-pinterest" href="/Admin/OfferPrices/index">
                        <i class="fa fa-backward"></i> بازگشت
                    </a>

                </div>

            </div>


        </div>

    }

</div>

SalinoMvc5/Areas/Admin/Views/OfferPrices/Delete.cshtml
@model Salino.Models.OfferPrice

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}



<section class="content-header">
    <h1 style="margin-bottom:15px">
        تخفیف چندمی به بعد

    </h1>
    <ol class="breadcrumb">
        <li><a href="/Admin/Default/Index"><i class="fa fa-dashboard"></i> مدیریت</a></li>
        <li class="active"> <a href="/Admin/OfferPrices/Index">   تخفیف چندمی به بعد</a></li>
        <li class="active">حذف  تخفیف  @Model.Price</li>
    </ol>
</section>


<div class="box box-info container">


    <h3>آیا  ازحذف      تخفیف  @Model.Price  مطمئن هستید؟ </h3>
    <div>

        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>
            <hr />
            <dt>
                @Html.DisplayNameFor(model => model.AsNumber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AsNumber)
            </dd>

            <hr />
        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">

                        <button class="btn btn-social btn-success" type="submit">
                            <i class="fa fa-save"></i> حذف
                        </button>
                        <a class="btn btn-social btn-pinterest" href="/Admin/OfferPrices/index">
                            <i class="fa fa-backward"></i> بازگشت
                        </a>

                    </div>
                </div>
            </div>
        }
    </div>
</div>

SalinoMvc5/Areas/Admin/Views/OfferPrices/Details.cshtml
@model Salino.Models.OfferPrice

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="content-header">
    <h1 style="margin-bottom:15px">
        تخفیف چندمی به بعد

    </h1>
    <ol class="breadcrumb">
        <li><a href="/Admin/Default/Index"><i class="fa fa-dashboard"></i> مدیریت</a></li>
        <li class="active"> <a href="/Admin/OfferPrices/Index"> تخفیف اولین خرید</a></li>
        <li class="active">جزئیات   تخفیف چندمی به بعد @Model.Price</li>
    </ol>
</section>

<div class="box box-info container">
    <div>
        <h4>جزئیات  تخفیف  @Model.Price</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>
            <hr />
            <dt>
                @Html.DisplayNameFor(model => model.AsNumber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AsNumber)
            </dd>
            <hr />
        </dl>
    </div>
    <p>
        <a class="btn btn-social btn-danger" href="/Admin/OfferPrices/Edit/@Model.Id">
            <i class="fa fa-backward"></i> ویرایش
        </a>
        <a class="btn btn-social btn-pinterest" href="/Admin/OfferPrices/index">
            <i class="fa fa-backward"></i> بازگشت
        </a>
    </p>
</div>

SalinoMvc5/Areas/Admin/Views/OfferPrices/Edit.cshtml
@model Salino.Models.OfferPrice

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="content-header">
    <h1 style="margin-bottom:15px">
        تخفیف چندمی به بعد

    </h1>
    <ol class="breadcrumb">
        <li><a href="/Admin/Default/Index"><i class="fa fa-dashboard"></i> مدیریت</a></li>
        <li class="active"> <a href="/Admin/OfferPrices/Index">            تخفیف چندمی به بعد</a></li>
        <li class="active">ویرایش   تخفیف  @Model.Price</</li>
    </ol>
</section>

<div class="box box-info container">


    @using (Html.BeginForm("Edit", "OfferPrices"))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => x.Id)
        <div class="form-horizontal">
            <h4>ویرایش   تخفیف @Model.Price</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AsNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AsNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AsNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <hr />
            <hr />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button class="btn btn-social btn-success" type="submit">
                        <i class="fa fa-save"></i> ویرایش
                    </button>
                    <a class="btn btn-social btn-pinterest" href="/Admin/OfferPrices/index">
                        <i class="fa fa-backward"></i> بازگشت
                    </a>
                </div>
            </div>
        </div>
    }



</div>

SalinoMvc5/Areas/Admin/Views/OfferPrices/Index.cshtml
@model IEnumerable<Salino.Models.OfferPrice>
@using Salino.DataLayer;
@{

    SalinoContext db = new SalinoContext();
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    int counter = 1;
}

<section class="content-header">
    <h1>
        تخفیف چندمی به بعد
        @if (db.OfferPrices.Count() < 2)
        {
            <a class="btn btn-app" href="/Admin/OfferPrices/Create">
                <i class="fa fa-hand-pointer-o"></i>         تخفیف  جدید
            </a>
        }
      


        <a class="btn btn-app" href="/Admin/OfferPrices/Index">
            <i class="fa fa-repeat"></i> به روزرسانی
        </a>
    </h1>
    <ol class="breadcrumb">
        <li><a href="/Admin/Default/Index"><i class="fa fa-dashboard"></i> مدیریت</a></li>
        <li class="active"> <a href="/Admin/OfferPrices/Index">   تخفیف چندمی به بعد</a> </li>
    </ol>
</section>

<section class="content  ">

    <div class="row">
        <div class="col-xs-12">
            <div class="box box box-info">
                <div class="box-header">
                    <h3 class="box-title">   تخفیف چندمی به بعد</h3>

                    <div class="box-tools">
                  
                    </div>

                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <tbody>
                            <tr>
                                <th>شماره</th>
                                <th> تخفیف</th>
                                <th>چندمی به بعد</th>


                            </tr>
                            @foreach (var item in Model)
                            {
                                <tr role="row" class="table-striped table-hover">
                                    <td class="sorting_1">@counter</td>
                                    <td>
                                        @item.Price  تومان
                                    </td>
                                    <td>

                                     @item.AsNumber 
                                    </td>

                                    <td>
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-info btn-flat dropdown-toggle" data-toggle="dropdown">عملیات</button>
                                            <button type="button" class="btn btn-info btn-flat dropdown-toggle" data-toggle="dropdown">
                                                <span class="caret"></span>
                                                <span class="sr-only">Toggle Dropdown</span>
                                            </button>
                                            <ul class="dropdown-menu" role="menu">
                                                <li>@Html.ActionLink("ویرایش", "Edit", new { id = item.Id }, new { @class = "btn btn-block btn-danger btn-flat", @style = "color:white" })</li>
                                                <li>@Html.ActionLink("جزئیات", "Details", new { id = item.Id }, new { @class = "btn btn-block btn-info btn-flat", @style = "color:white" })</li>
                                                <li>
                                                    @Html.ActionLink("حذف", "Delete", new { id = item.Id }, new { @class = "btn btn-block btn-warning btn-flat", @style = "color:white" })

                                                </li>

                                            </ul>
                                        </div>

                                    </td>

                                </tr>
                                counter++;
                            }

                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>

</section>