SalinoMvc5/Areas/Admin/Controllers/Offers/SendPricesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Salino.DataLayer;
using Salino.Models;

namespace SalinoMvc5.Areas.Admin.Controllers.Offers
{
    [Authorize(Roles = "Admin1")]
    public class SendPricesController : Controller
    {
        private SalinoContext db = new SalinoContext();

        // GET: Admin/SendPrices
        public ActionResult Index()
        {
            var result = db.SendPrices.Where(x => x.AsNumber != 0);
            return View(result.ToList());
        }

        // GET: Admin/SendPrices/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SendPrice sendPrice = db.SendPrices.Find(id);
            if (sendPrice == null)
            {
                return HttpNotFound();
            }
            return View(sendPrice);
        }

        // GET: Admin/SendPrices/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/SendPrices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( SendPrice sendPrice)
        {
            if (ModelState.IsValid)
            {
                db.SendPrices.Add(sendPrice);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sendPrice);
        }

        // GET: Admin/SendPrices/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SendPrice sendPrice = db.SendPrices.Find(id);
            if (sendPrice == null)
            {
                return HttpNotFound();
            }
            return View(sendPrice);
        }

        // POST: Admin/SendPrices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( SendPrice sendPrice)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sendPrice).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sendPrice);
        }

        // GET: Admin/SendPrices/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SendPrice sendPrice = db.SendPrices.Find(id);
            if (sendPrice == null)
            {
                return HttpNotFound();
            }
            return View(sendPrice);
        }

        // POST: Admin/SendPrices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SendPrice sendPrice = db.SendPrices.Find(id);
            db.SendPrices.Remove(sendPrice);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SalinoMvc5/Areas/Admin/Views/SendPrices/Create.cshtml
@model Salino.Models.SendPrice
@using  Salino.ToShamsi()
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="content-header">
    <h1 style="margin-bottom:15px">
        ارسال پست رایگان

    </h1>
    <ol class="breadcrumb">
        <li><a href="/Admin/Default/Index"><i class="fa fa-dashboard"></i> مدیریت</a></li>
        <li class="active"><a href="/Admin/SendPrices/Index">  ارسال پست رایگان     </a></li>  
        <li class="active">ارسال پست رایگان جدید</li>
    </ol>
</section>
<div class="box box-info container">


    @using (Html.BeginForm("Create", "SendPrices"))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>ارسال پست رایگان جدید</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    

            <div class="form-group">
                @Html.LabelFor(model => model.AsNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="">
                        @Html.EditorFor(model => model.AsNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AsNumber, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <hr />


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button class="btn btn-social btn-success" type="submit">
                        <i class="fa fa-save"></i> ذخیره
                    </button>
                    <a class="btn btn-social btn-pinterest" href="/Admin/SendPrices/index">
                        <i class="fa fa-backward"></i> بازگشت
                    </a>
                </div>
            </div>
        </div>

    }

</div>

SalinoMvc5/Areas/Admin/Views/SendPrices/Delete.cshtml
@model Salino.Models.SendPrice

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<section class="content-header">
    <h1 style="margin-bottom:15px">
        ارسال پست رایگان

    </h1>
    <ol class="breadcrumb">
        <li><a href="/Admin/Default/Index"><i class="fa fa-dashboard"></i> مدیریت</a></li>
        <li class="active"><a href="/Admin/SendPrices/Index">        ارسال پست رایگان</a></li>
        <li class="active">حذف ارسال پست رایگان </li>
    </ol>
</section>
<div class="box box-info container">


    <h3>آیا  ازحذف   مطمئن هستید؟ </h3>
    <div>

        <hr />
        <dl class="dl-horizontal">
       

            <dt>
                @Html.DisplayNameFor(model => model.AsNumber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AsNumber)
            </dd>
            <hr />
        


        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">

                        <button class="btn btn-social btn-success" type="submit">
                            <i class="fa fa-save"></i> حذف
                        </button>
                        <a class="btn btn-social btn-pinterest" href="/Admin/SendPrices/index">
                            <i class="fa fa-backward"></i> بازگشت
                        </a>

                    </div>
                </div>
            </div>
        }
    </div>
</div>

SalinoMvc5/Areas/Admin/Views/SendPrices/Edit.cshtml
@model Salino.Models.SendPrice

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<section class="content-header">
    <h1 style="margin-bottom:15px">
        ارسال پست رایگان

    </h1>
    <ol class="breadcrumb">
        <li><a href="/Admin/Default/Index"><i class="fa fa-dashboard"></i> مدیریت</a></li>
        <li class="active"><a href="/Admin/SendPrices/Index"> ارسال پست رایگان</a></li>
        <li class="active">ویرایش  ارسال پست رایگان </li>
    </ol>
</section>
<div class="box box-info container">


    @using (Html.BeginForm("Edit", "SendPrices"))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => x.Id)


        <div class="form-horizontal">
            <h4>ویرایش  ارسال پست رایگان</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)


            <div class="form-group">
                @Html.LabelFor(model => model.AsNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="">
                        @Html.EditorFor(model => model.AsNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AsNumber, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <hr />

       

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button class="btn btn-social btn-success" type="submit">
                        <i class="fa fa-save"></i> ویرایش
                    </button>
                    <a class="btn btn-social btn-pinterest" href="/Admin/SendPrices/index">
                        <i class="fa fa-backward"></i> بازگشت
                    </a>
                </div>
            </div>
        </div>
    }


</div>

SalinoMvc5/Areas/Admin/Views/SendPrices/Index.cshtml
@model IEnumerable<Salino.Models.SendPrice>
@using Salino.DataLayer;
@{

    SalinoContext db = new SalinoContext();

    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    int counter = 1;
}

<section class="content-header">
    <h1>
        صفحه اصلی
    @if (db.SendPrices.Count() < 2)
    {
        <a class="btn btn-app" href="/Admin/SendPrices/Create">
            <i class="fa fa-hand-pointer-o"></i>   جدید
        </a>
    }
          
        <a class="btn btn-app" href="/Admin/SendPrices/Index">
            <i class="fa fa-repeat"></i> به روزرسانی
        </a>
    </h1>
    <ol class="breadcrumb">
        <li><a href="/Admin/Default/Index"><i class="fa fa-dashboard"></i> مدیریت</a></li>
        <li class="active"><a href="/Admin/SendPrices/Index">    ارسال پست رایگان</a></li>
    </ol>
</section>

<section class="content  ">

    <div class="row">
        <div class="col-xs-12">
            <div class="box box box-info">
                <div class="box-header">
                    <h3 class="box-title"> ارسال پست رایگان</h3>

                    <div class="box-tools">
                     
                    </div>

                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <tbody>
                            <tr>
                                <th>شماره</th>
                                <th>چندمین انتخاب  برای ارسال رایگان</th>
                     
            
                            </tr>
                            @foreach (var item in Model)
                            {
                                <tr role="row" class="table-striped table-hover">
                                    <td class="sorting_1">@counter</td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.AsNumber)
                                    </td>                                
                                 
                                    <td>
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-info btn-flat dropdown-toggle" data-toggle="dropdown">عملیات</button>
                                            <button type="button" class="btn btn-info btn-flat dropdown-toggle" data-toggle="dropdown">
                                                <span class="caret"></span>
                                                <span class="sr-only">Toggle Dropdown</span>
                                            </button>
                                            <ul class="dropdown-menu" role="menu">
                                                <li>@Html.ActionLink("ویرایش", "Edit", new { id = item.Id }, new { @class = "btn btn-block btn-danger btn-flat", @style = "color:white" })</li>
                                              
                                                <li>
                                                    @Html.ActionLink("حذف", "Delete", new { id = item.Id }, new { @class = "btn btn-block btn-warning btn-flat", @style = "color:white" })



                                                </li>

                                            </ul>
                                        </div>

                                    </td>

                                </tr>
                                counter++;
                            }

                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>

</section>