SalinoMvc5/Areas/Admin/Controllers/MojavezsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Salino.DataLayer;
using Salino.Models;
using System.Web.Helpers;

namespace SalinoMvc5.Areas.Admin.Controllers
{
    public class MojavezsController : Controller
    {
        private SalinoContext db = new SalinoContext();

        // GET: Admin/Mojavezs
        public ActionResult Index()
        {
            return View(db.Mojavezs.ToList());
        }

        // GET: Admin/Mojavezs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mojavez mojavez = db.Mojavezs.Find(id);
            if (mojavez == null)
            {
                return HttpNotFound();
            }
            return View(mojavez);
        }

        // GET: Admin/Mojavezs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Mojavezs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ListKhadamat,Img1,Img2,Img3")] Mojavez mojavez, HttpPostedFileBase file1, HttpPostedFileBase file2, HttpPostedFileBase file3)
        {
            if (ModelState.IsValid)
            {
                if (file1 != null)
                {
                    Random random = new Random();
                    string imgcode = random.Next(100000, 999000).ToString();
                    string imgname = "mojavez";
                    WebImage img = new WebImage(file1.InputStream);
                    string imgsrc3 = "mojavez" + "-" + imgname + "-" + imgcode.ToString() + "-" + file1.FileName;

                    img.Save("~/Content/imgMojavez/" + imgsrc3);
                    mojavez.Img1 = imgsrc3;
                }
                if (file2 != null)
                {
                    Random random = new Random();
                    string imgcode = random.Next(100000, 999000).ToString();
                    string imgname = "mojavez";
                    WebImage img = new WebImage(file2.InputStream);
                    string imgsrc3 = "mojavez" + "-" + imgname + "-" + imgcode.ToString() + "-" + file2.FileName;

                    img.Save("~/Content/imgMojavez/" + imgsrc3);
                    mojavez.Img2 = imgsrc3;
                }
                if (file3 != null)
                {
                    Random random = new Random();
                    string imgcode = random.Next(100000, 999000).ToString();
                    string imgname = "mojavez";
                    WebImage img = new WebImage(file3.InputStream);
                    string imgsrc3 = "mojavez" + "-" + imgname + "-" + imgcode.ToString() + "-" + file3.FileName;

                    img.Save("~/Content/imgMojavez/" + imgsrc3);
                    mojavez.Img3 = imgsrc3;
                }
                db.Mojavezs.Add(mojavez);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(mojavez);
        }

        // GET: Admin/Mojavezs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mojavez mojavez = db.Mojavezs.Find(id);
            if (mojavez == null)
            {
                return HttpNotFound();
            }
            return View(mojavez);
        }

        // POST: Admin/Mojavezs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ListKhadamat,Img1,Img2,Img3")] Mojavez mojavez, HttpPostedFileBase file1, HttpPostedFileBase file2, HttpPostedFileBase file3)
        {
            if (ModelState.IsValid)
            {
                if (file1 != null)
                {
                    if (System.IO.File.Exists(Server.MapPath("~/Content/imgMojavez/" + mojavez.Img1)))
                    {
                        System.IO.File.Delete(Server.MapPath("~/Content/imgMojavez/" + mojavez.Img1));
                    }
                    Random random = new Random();
                    string imgcode = random.Next(100000, 999000).ToString();
                    string imgname = "mojavez";
                    WebImage img = new WebImage(file1.InputStream);
                    string imgsrc3 = "mojavez" + "-" + imgname + "-" + imgcode.ToString() + "-" + file1.FileName;

                    img.Save("~/Content/imgMojavez/" + imgsrc3);
                    mojavez.Img1 = imgsrc3;
                }
                if (file2 != null)
                {
                    if (System.IO.File.Exists(Server.MapPath("~/Content/imgMojavez/" + mojavez.Img2)))
                    {
                        System.IO.File.Delete(Server.MapPath("~/Content/imgMojavez/" + mojavez.Img2));
                    }
                    Random random = new Random();
                    string imgcode = random.Next(100000, 999000).ToString();
                    string imgname = "mojavez";
                    WebImage img = new WebImage(file2.InputStream);
                    string imgsrc3 = "mojavez" + "-" + imgname + "-" + imgcode.ToString() + "-" + file2.FileName;

                    img.Save("~/Content/imgMojavez/" + imgsrc3);
                    mojavez.Img2 = imgsrc3;
                }
                if (file3 != null)
                {
                    if (System.IO.File.Exists(Server.MapPath("~/Content/imgMojavez/" + mojavez.Img3)))
                    {
                        System.IO.File.Delete(Server.MapPath("~/Content/imgMojavez/" + mojavez.Img3));
                    }
                    Random random = new Random();
                    string imgcode = random.Next(100000, 999000).ToString();
                    string imgname = "mojavez";
                    WebImage img = new WebImage(file3.InputStream);
                    string imgsrc3 = "mojavez" + "-" + imgname + "-" + imgcode.ToString() + "-" + file3.FileName;

                    img.Save("~/Content/imgMojavez/" + imgsrc3);
                    mojavez.Img3 = imgsrc3;
                }
                db.Entry(mojavez).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mojavez);
        }

        // GET: Admin/Mojavezs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mojavez mojavez = db.Mojavezs.Find(id);
            if (mojavez == null)
            {
                return HttpNotFound();
            }
            return View(mojavez);
        }

        // POST: Admin/Mojavezs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
          
            Mojavez mojavez = db.Mojavezs.Find(id);
            if (System.IO.File.Exists(Server.MapPath("~/Content/imgMojavez/" + mojavez.Img1)))
            {
                System.IO.File.Delete(Server.MapPath("~/Content/imgMojavez/" + mojavez.Img1));
            }
            if (System.IO.File.Exists(Server.MapPath("~/Content/imgMojavez/" + mojavez.Img2)))
            {
                System.IO.File.Delete(Server.MapPath("~/Content/imgMojavez/" + mojavez.Img2));
            }
            if (System.IO.File.Exists(Server.MapPath("~/Content/imgMojavez/" + mojavez.Img3)))
            {
                System.IO.File.Delete(Server.MapPath("~/Content/imgMojavez/" + mojavez.Img3));
            }
            db.Mojavezs.Remove(mojavez);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SalinoMvc5/Areas/Admin/Views/Mojavezs/Create.cshtml
@model Salino.Models.Mojavez

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<section class="content-header">
    <h1 style="margin-bottom:15px">
        مجوز ها

    </h1>
    <ol class="breadcrumb">
        <li><a href="/Admin/Default/Index"><i class="fa fa-dashboard"></i> مدیریت</a></li>
        <li class="active"><a href="/Admin/Mojavezs/Index">       مجوز ها</a></li>
        <li class="active">   خرید    مجوز ها</li>
    </ol>
</section>
<div class="box box-info container">


@using (Html.BeginForm("Create", "Mojavezs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>   خرید    مجوز ها</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            <div class="form-group">
                @Html.LabelFor(model => model.ListKhadamat, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ListKhadamat, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ListKhadamat, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Img1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input class="input-lg" type="file" name="file1" onchange="readURL1(this);" />
                    <img id="blah" src="~/Content/tn_WallpaperGram.IR_1561882027_z90271.jpg" alt="your image" style="height:auto;width:auto;" class="img-responsive img-thumbnail" />
                    <script>
                        function readURL1(input) {
                            if (input.files && input.files[0]) {
                                var reader = new FileReader();

                                reader.onload = function (e) {
                                    $('#blah')
                                        .attr('src', e.target.result);
                                };

                                reader.readAsDataURL(input.files[0]);
                            }
                        }
                    </script>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Img2, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input class="input-lg" type="file" name="file2" onchange="readURLdetailMob(this);" />
                    <img id="detailMob" src="~/Content/tn_WallpaperGram.IR_1561882027_z90271.jpg" alt="your image" style="height:auto;width:auto;" class="img-responsive img-thumbnail" />
                    <script>
                        function readURLdetailMob(input) {
                            if (input.files && input.files[0]) {
                                var reader = new FileReader();

                                reader.onload = function (e) {
                                    $('#detailMob')
                                        .attr('src', e.target.result);
                                };

                                reader.readAsDataURL(input.files[0]);
                            }
                        }
                    </script>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Img3, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input class="input-lg" type="file" name="file3" onchange="readURL2(this);" />
                    <img id="filemain" src="~/Content/tn_WallpaperGram.IR_1561882027_z90271.jpg" alt="your image" style="height:auto;width:auto;" class="img-responsive img-thumbnail" />
                    <script>
                        function readURL2(input) {
                            if (input.files && input.files[0]) {
                                var reader = new FileReader();

                                reader.onload = function (e) {
                                    $('#filemain')
                                        .attr('src', e.target.result);
                                };

                                reader.readAsDataURL(input.files[0]);
                            }
                        }
                    </script>
                </div>
            </div>
            <hr />

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button class="btn btn-social btn-success" type="submit">
                        <i class="fa fa-save"></i> ذخیره
                    </button>
                    <a class="btn btn-social btn-pinterest" href="/Admin/Mojavezs/index">
                        <i class="fa fa-backward"></i> بازگشت
                    </a>
                </div>
            </div>
        </div>

    }

</div>
@section scripts{

    <script src="~/Areas/Admin/content/bower_components/ckeditor/ckeditor.js"></script>
    <script src="~/Areas/Admin/content/bower_components/ckeditor/adapters/jquery.js"></script>


    <script>
        $(function () {
            $('#ListKhadamat').ckeditor();
        });
    </script>
}

SalinoMvc5/Areas/Admin/Views/Mojavezs/Delete.cshtml
@model Salino.Models.Mojavez

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<section class="content-header">
    <h1 style="margin-bottom:15px">
        مجوز ها

    </h1>
    <ol class="breadcrumb">
        <li><a href="/Admin/Default/Index"><i class="fa fa-dashboard"></i> مدیریت</a></li>
        <li class="active"><a href="/Admin/Mojavezs/Index">     مجوز ها</a></li>
        <li class="active">حذف      مجوز ها </li>
    </ol>
</section>
<div class="box box-info container">


    <h3>آیا  ازحذف   مطمئن هستید؟ </h3>
    <div>

        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ListKhadamat)
            </dt>

            <dd>
                @Html.Raw(Model.ListKhadamat)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Img1)
            </dt>

            <dd>
                <img src="~/Content/imgMojavez/@Model.Img3" alt="@Model.Img3 " class="img-thumbnail" style="border:1px solid ;width:120px;height:120px;" />
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Img2)
            </dt>

            <dd>
                <img src="~/Content/imgMojavez/@Model.Img3" alt="@Model.Img3 " class="img-thumbnail" style="border:1px solid ;width:120px;height:120px;" />
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Img3)
            </dt>

            <dd>
                <img src="~/Content/imgMojavez/@Model.Img3" alt="@Model.Img3 " class="img-thumbnail" style="border:1px solid ;width:120px;height:120px;" />
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">

                        <button class="btn btn-social btn-success" type="submit">
                            <i class="fa fa-save"></i> حذف
                        </button>
                        <a class="btn btn-social btn-pinterest" href="/Admin/Mojavezs/index">
                            <i class="fa fa-backward"></i> بازگشت
                        </a>

                    </div>
                </div>
            </div>
        }
    </div>
</div>

SalinoMvc5/Areas/Admin/Views/Mojavezs/Details.cshtml
@model Salino.Models.Mojavez

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<section class="content-header">
    <h1 style="margin-bottom:15px">
     مجوز ها

    </h1>
    <ol class="breadcrumb">
        <li><a href="/Admin/Default/Index"><i class="fa fa-dashboard"></i> مدیریت</a></li>
        <li class="active"><a href="/Admin/Mojavezs/Index">  مجوز ها</a></li>
        <li class="active">      مجوز ها</li>
    </ol>
</section>
<div class="box box-info container">

    <div>
        <h4>جزئیات  مجوز ها </h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ListKhadamat)
            </dt>

            <dd>
                @Html.Raw(Model.ListKhadamat)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Img1)
            </dt>

            <dd>
                <img src="~/Content/imgMojavez/@Model.Img3" alt="@Model.Img3 " class="img-thumbnail" style="border:1px solid ;width:120px;height:120px;" />
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Img2)
            </dt>

            <dd>
                <img src="~/Content/imgMojavez/@Model.Img3" alt="@Model.Img3 " class="img-thumbnail" style="border:1px solid ;width:120px;height:120px;" />
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Img3)
            </dt>

            <dd>
                <img src="~/Content/imgMojavez/@Model.Img3" alt="@Model.Img3 " class="img-thumbnail" style="border:1px solid ;width:120px;height:120px;" />
            </dd>

        </dl>
    </div>

    <p>
        <a class="btn btn-social btn-danger" href="/Admin/Mojavezs/Edit/@Model.Id">
            <i class="fa fa-backward"></i> ویرایش
        </a>
        <a class="btn btn-social btn-pinterest" href="/Admin/Mojavezs/index">
            <i class="fa fa-backward"></i> بازگشت
        </a>
    </p>
</div>

SalinoMvc5/Areas/Admin/Views/Mojavezs/Edit.cshtml
@model Salino.Models.Mojavez

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}




<section class="content-header">
    <h1 style="margin-bottom:15px">
        خرید عمده

    </h1>
    <ol class="breadcrumb">
        <li><a href="/Admin/Default/Index"><i class="fa fa-dashboard"></i> مدیریت</a></li>
        <li class="active"><a href="/Admin/Mojavezs/Index">مجوز ها</a></li>
        <li class="active">ویرایش مجوز ها</li>
    </ol>
</section>
<div class="box box-info container">


@using (Html.BeginForm("Edit", "Mojavezs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(x => x.Img1)
    @Html.HiddenFor(x => x.Img2)
    @Html.HiddenFor(x => x.Img3)
        <div class="form-group">
            @Html.LabelFor(model => model.ListKhadamat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ListKhadamat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ListKhadamat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Img1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                تصویرجاری:   <img src="~/Content/imgMojavez/@Model.Img1" alt="@Model.Img1 " class="img-responsive img-thumbnail" style="border:1px solid ;width:120px;height:120px;" />

                <input class="input-lg" type="file" name="file1" onchange="readURL1(this);" />
                <img id="blah" src="~/Content/tn_WallpaperGram.IR_1561882027_z90271.jpg" alt="your image" style="height:auto;width:auto;" class="img-responsive img-thumbnail" />
                <script>
                        function readURL1(input) {
                            if (input.files && input.files[0]) {
                                var reader = new FileReader();

                                reader.onload = function (e) {
                                    $('#blah')
                                        .attr('src', e.target.result);
                                };

                                reader.readAsDataURL(input.files[0]);
                            }
                        }
                </script>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Img2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                تصویرجاری:   <img src="~/Content/imgMojavez/@Model.Img2" alt="@Model.Img2 " class="img-responsive img-thumbnail" style="border:1px solid ;width:120px;height:120px;" />
                <input class="input-lg" type="file" name="file2" onchange="readURLdetailMob(this);" />
                <img id="detailMob" src="~/Content/tn_WallpaperGram.IR_1561882027_z90271.jpg" alt="your image" style="height:auto;width:auto;" class="img-responsive img-thumbnail" />
                <script>
                        function readURLdetailMob(input) {
                            if (input.files && input.files[0]) {
                                var reader = new FileReader();

                                reader.onload = function (e) {
                                    $('#detailMob')
                                        .attr('src', e.target.result);
                                };

                                reader.readAsDataURL(input.files[0]);
                            }
                        }
                </script>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Img3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                تصویرجاری:   <img src="~/Content/imgMojavez/@Model.Img3" alt="@Model.Img3 " class="img-responsive img-thumbnail" style="border:1px solid ;width:120px;height:120px;" />
                <input class="input-lg" type="file" name="file3" onchange="readURL2(this);" />
                <img id="filemain" src="~/Content/tn_WallpaperGram.IR_1561882027_z90271.jpg" alt="your image" style="height:auto;width:auto;" class="img-responsive img-thumbnail" />
                <script>
                        function readURL2(input) {
                            if (input.files && input.files[0]) {
                                var reader = new FileReader();

                                reader.onload = function (e) {
                                    $('#filemain')
                                        .attr('src', e.target.result);
                                };

                                reader.readAsDataURL(input.files[0]);
                            }
                        }
                </script>
            </div>
        </div>

        <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button class="btn btn-social btn-success" type="submit">
                        <i class="fa fa-save"></i> ویرایش
                    </button>
                    <a class="btn btn-social btn-pinterest" href="/Admin/Mojavezs/index">
                        <i class="fa fa-backward"></i> بازگشت
                    </a>
                </div>
            </div>

}


</div>
@section scripts{

    <script src="~/Areas/Admin/content/bower_components/ckeditor/ckeditor.js"></script>
    <script src="~/Areas/Admin/content/bower_components/ckeditor/adapters/jquery.js"></script>


    <script>
        $(function () {
            $('#ListKhadamat').ckeditor();
        });
    </script>
}

SalinoMvc5/Areas/Admin/Views/Mojavezs/Index.cshtml
@model IEnumerable<Salino.Models.Mojavez>
@using Salino.DataLayer;
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    int counter = 1;
    SalinoContext db = new SalinoContext();
}




<section class="content-header">
    <h1>
        صفحه اصلی
        @if (db.Mojavezs.Count() < 1)
        {
            <a class="btn btn-app" href="/Admin/Mojavezs/Create">
                <i class="fa fa-hand-pointer-o"></i> مجوز جدید
            </a>
        }
   
        <a class="btn btn-app" href="/Admin/Mojavezs/Index">
            <i class="fa fa-repeat"></i> به روزرسانی
        </a>
    </h1>
    <ol class="breadcrumb">
        <li><a href="/Admin/Default/Index"><i class="fa fa-dashboard"></i> مدیریت</a></li>
        <li class="active"><a href="/Admin/Mojavezs/Index">  مجوز ها</a></li>
    </ol>
</section>

<section class="content  ">

    <div class="row">
        <div class="col-xs-12">
            <div class="box box box-info">
                <div class="box-header">
                    <h3 class="box-title"> مجوز ها</h3>

                    <div class="box-tools">

                    </div>

                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <tbody>
                            <tr>
                                <th>شماره</th>
                              
                                <th>
                                    @Html.DisplayNameFor(model => model.Img1)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Img2)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Img3)
                                </th>
                            </tr>
                            @foreach (var item in Model)
                            {
                                <tr role="row" class="table-striped table-hover">
                                    <td class="sorting_1">@counter</td>
                                 
                                    <td>
                                        <img src="~/Content/imgMojavez/@item.Img1" alt="@item.Img1 " class="img-thumbnail" style="border:1px solid ;width:120px;height:120px;" />
                                    </td>
                                    <td>
                                        <img src="~/Content/imgMojavez/@item.Img2" alt="@item.Img2 " class="img-thumbnail" style="border:1px solid ;width:120px;height:120px;" />
                                    </td>
                                    <td>
                                        <img src="~/Content/imgMojavez/@item.Img3" alt="@item.Img3 " class="img-thumbnail" style="border:1px solid ;width:120px;height:120px;" />
                                    </td>
                                    <td>
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-info btn-flat dropdown-toggle" data-toggle="dropdown">عملیات</button>
                                            <button type="button" class="btn btn-info btn-flat dropdown-toggle" data-toggle="dropdown">
                                                <span class="caret"></span>
                                                <span class="sr-only">Toggle Dropdown</span>
                                            </button>
                                            <ul class="dropdown-menu" role="menu">
                                                <li>@Html.ActionLink("ویرایش", "Edit", new { id = item.Id }, new { @class = "btn btn-block btn-danger btn-flat", @style = "color:white" })</li>
                                                <li>@Html.ActionLink("جزئیات", "Details", new { id = item.Id }, new { @class = "btn btn-block btn-info btn-flat", @style = "color:white" })</li>
                                                <li>
                                                    @Html.ActionLink("حذف", "Delete", new { id = item.Id }, new { @class = "btn btn-block btn-warning btn-flat", @style = "color:white" })



                                                </li>

                                            </ul>
                                        </div>

                                    </td>

                                </tr>
                                counter++;
                            }

                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>

</section>