SalinoMvc5/Areas/Admin/Controllers/Monasebats/MonasebatProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Salino.DataLayer;
using Salino.Models;

namespace SalinoMvc5.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin1")]
    public class MonasebatProductsController : Controller
    {
        private SalinoContext db = new SalinoContext();

        // GET: Admin/MonasebatProducts
        public ActionResult Index(string search)
        {
            if (!string.IsNullOrEmpty(search))
            {
                var Monasebats = db.MonasebatProducts.Where(x => x.Monasebats.MonasebatTitle.Contains(search)||x.Products.CodeKala.Contains(search)).Include(m => m.Monasebats).Include(m => m.Products).ToList();
                return View(Monasebats);
            }
            else
            {
                var monasebatProducts = db.MonasebatProducts.Include(m => m.Monasebats).Include(m => m.Products);
                return View(monasebatProducts.ToList());
            }

        }

        // GET: Admin/MonasebatProducts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MonasebatProducts monasebatProducts = db.MonasebatProducts.Find(id);
            if (monasebatProducts == null)
            {
                return HttpNotFound();
            }
            return View(monasebatProducts);
        }

        // GET: Admin/MonasebatProducts/Create
        public ActionResult Create()
        {
            ViewBag.MonasebatId = new SelectList(db.Monasebats, "Id", "MonasebatTitle");
            ViewBag.ProductId = new SelectList(db.Products, "Id", "CodeKala");
            return View();
        }

        // POST: Admin/MonasebatProducts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,MonasebatId,ProductId")] MonasebatProducts monasebatProducts)
        {
            if (ModelState.IsValid)
            {
                db.MonasebatProducts.Add(monasebatProducts);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MonasebatId = new SelectList(db.Monasebats, "Id", "MonasebatTitle", monasebatProducts.MonasebatId);
            ViewBag.ProductId = new SelectList(db.Products, "Id", "CodeKala", monasebatProducts.ProductId);
            return View(monasebatProducts);
        }

        // GET: Admin/MonasebatProducts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MonasebatProducts monasebatProducts = db.MonasebatProducts.Find(id);
            if (monasebatProducts == null)
            {
                return HttpNotFound();
            }
            ViewBag.MonasebatId = new SelectList(db.Monasebats, "Id", "MonasebatTitle", monasebatProducts.MonasebatId);
            ViewBag.ProductId = new SelectList(db.Products, "Id", "CodeKala", monasebatProducts.ProductId);
            return View(monasebatProducts);
        }

        // POST: Admin/MonasebatProducts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,MonasebatId,ProductId")] MonasebatProducts monasebatProducts)
        {
            if (ModelState.IsValid)
            {
                db.Entry(monasebatProducts).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MonasebatId = new SelectList(db.Monasebats, "Id", "MonasebatTitle", monasebatProducts.MonasebatId);
            ViewBag.ProductId = new SelectList(db.Products, "Id", "CodeKala", monasebatProducts.ProductId);
            return View(monasebatProducts);
        }

        // GET: Admin/MonasebatProducts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MonasebatProducts monasebatProducts = db.MonasebatProducts.Find(id);
            if (monasebatProducts == null)
            {
                return HttpNotFound();
            }
            return View(monasebatProducts);
        }

        // POST: Admin/MonasebatProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MonasebatProducts monasebatProducts = db.MonasebatProducts.Find(id);
            db.MonasebatProducts.Remove(monasebatProducts);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public int DeleteAll(string [] checkedNames)
        {
            foreach (var item in checkedNames)
            {
               
                int id = int.Parse(item);
                MonasebatProducts monasebatProducts = db.MonasebatProducts.Find(id);
                db.MonasebatProducts.Remove(monasebatProducts);
                db.SaveChanges();

            }
        
            return 1;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SalinoMvc5/Areas/Admin/Controllers/Monasebats/MonasebatsApiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using Salino.DataLayer;
using Salino.Models;

namespace SalinoMvc5.Areas.Admin.Controllers.Monasebats
{
    public class MonasebatsApiController : ApiController
    {
        private SalinoContext db = new SalinoContext();

        // GET: api/MonasebatsApi
        public IQueryable<Monasebat> GetMonasebats()
        {
            return db.Monasebats;
        }

        // GET: api/MonasebatsApi/5
        [ResponseType(typeof(Monasebat))]
        public IHttpActionResult GetMonasebat(int id)
        {
            Monasebat monasebat = db.Monasebats.Find(id);
            if (monasebat == null)
            {
                return NotFound();
            }

            return Ok(monasebat);
        }

        // PUT: api/MonasebatsApi/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutMonasebat(int id, Monasebat monasebat)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != monasebat.Id)
            {
                return BadRequest();
            }

            db.Entry(monasebat).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MonasebatExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/MonasebatsApi
        [ResponseType(typeof(Monasebat))]
        public void PostMonasebat(Monasebat monasebat)
        {
           

            db.Monasebats.Add(monasebat);
            db.SaveChanges();

           
        }

        // DELETE: api/MonasebatsApi/5
        [ResponseType(typeof(Monasebat))]
        public IHttpActionResult DeleteMonasebat(int id)
        {
            Monasebat monasebat = db.Monasebats.Find(id);
            if (monasebat == null)
            {
                return NotFound();
            }

            db.Monasebats.Remove(monasebat);
            db.SaveChanges();

            return Ok(monasebat);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool MonasebatExists(int id)
        {
            return db.Monasebats.Count(e => e.Id == id) > 0;
        }
    }
}

SalinoMvc5/Areas/Admin/Controllers/Monasebats/MonasebatsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Salino.DataLayer;
using Salino.Models;

namespace SalinoMvc5.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin1")]
    public class MonasebatsController : Controller
    {
        private SalinoContext db = new SalinoContext();

        // GET: Admin/Monasebats
        public ActionResult Index(string search)
        {
            if (!string.IsNullOrEmpty(search))
            {
                var Monasebats = db.Monasebats.Where(x => x.MonasebatTitle.Contains(search)).ToList();
                return View(Monasebats);
            }
            else
            {
                return View(db.Monasebats.ToList());
            }
           
        }
        public ActionResult DetailsProducts(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Monasebat Monasebat = db.Monasebats.Find(id);
            var productmonasebat = db.MonasebatProducts.Where(x => x.MonasebatId == Monasebat.Id).ToList();
            ViewBag.monasebat = Monasebat.MonasebatTitle;
            if (Monasebat == null)
            {
                return HttpNotFound();
            }
            return View(productmonasebat);
        }
        // GET: Admin/Monasebats/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Monasebat monasebat = db.Monasebats.Find(id);
            if (monasebat == null)
            {
                return HttpNotFound();
            }
            return View(monasebat);
        }

        // GET: Admin/Monasebats/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Monasebats/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,MonasebatTitle")] Monasebat monasebat)
        {
            if (ModelState.IsValid)
            {
                db.Monasebats.Add(monasebat);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(monasebat);
        }

        // GET: Admin/Monasebats/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Monasebat monasebat = db.Monasebats.Find(id);
            if (monasebat == null)
            {
                return HttpNotFound();
            }
            return View(monasebat);
        }

        // POST: Admin/Monasebats/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,MonasebatTitle")] Monasebat monasebat)
        {
            if (ModelState.IsValid)
            {
                db.Entry(monasebat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(monasebat);
        }

        // GET: Admin/Monasebats/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Monasebat monasebat = db.Monasebats.Find(id);
            if (monasebat == null)
            {
                return HttpNotFound();
            }
            return View(monasebat);
        }

        // POST: Admin/Monasebats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Monasebat monasebat = db.Monasebats.Find(id);
            db.Monasebats.Remove(monasebat);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult ShowMonasebats()
        {
            return PartialView("_ShowMonasebats");
        }
        public ActionResult AddMonasebat()
        {
            return PartialView("_AddMonasebat");
        }
    }
}

SalinoMvc5/Areas/Admin/Views/Monasebats/Create.cshtml
@model Salino.Models.Monasebat

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="content-header">
    <h1 style="margin-bottom:15px">
        مناسبت ها

    </h1>
    <ol class="breadcrumb">
        <li><a href="/Admin/Default/Index"><i class="fa fa-dashboard"></i> مدیریت</a></li>
        <li class="active"><a href="/Admin/Monasebats/Index">   مناسبت ها</a></li>
        <li class="active">مناسبت جدید</li>
    </ol>
</section>
<div class="box box-info container">


    @using (Html.BeginForm("Create", "Monasebats", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>مناسبت جدید</h4>

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.MonasebatTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MonasebatTitle, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MonasebatTitle, "", new { @class = "text-danger" })
                </div>
            </div>
            <hr />


         

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">

                    <button class="btn btn-social btn-success" type="submit">
                        <i class="fa fa-save"></i> ذخیره
                    </button>
                    <a class="btn btn-social btn-pinterest" href="/Admin/Monasebats/index">
                        <i class="fa fa-backward"></i> بازگشت
                    </a>

                </div>
            </div>



        </div>

    }

</div>

SalinoMvc5/Areas/Admin/Views/Monasebats/Details.cshtml
@model Salino.Models.Monasebat

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<section class="content-header">
    <h1 style="margin-bottom:15px">
        مناسبت ها

    </h1>
    <ol class="breadcrumb">
        <li><a href="/Admin/Default/Index"><i class="fa fa-dashboard"></i> مدیریت</a></li>
        <li class="active"><a href="/Admin/Monasebats/Index">       مناسبت ها</a></li>
        <li class="active">جزئیات مناسبت @Model.MonasebatTitle</li>
    </ol>
</section>
<div class="box box-info container">

    <div>
        <h4>جزئیات مناسبت @Model.MonasebatTitle</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.MonasebatTitle)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MonasebatTitle)
            </dd>
            <hr />

          
           

        </dl>
    </div>

    <p>
        <a class="btn btn-social btn-danger" href="/Admin/Monasebats/Edit/@Model.Id">
            <i class="fa fa-backward"></i> ویرایش
        </a>
        <a class="btn btn-social btn-pinterest" href="/Admin/Monasebats/index">
            <i class="fa fa-backward"></i> بازگشت
        </a>
    </p>
</div>

SalinoMvc5/Areas/Admin/Views/Monasebats/DetailsProducts.cshtml
@model IEnumerable<Salino.Models.MonasebatProducts>

@{
    ViewBag.Title = "DetailsProducts";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    int counter = 1;
}

<section class="content-header">
    <h1 style="margin-bottom:15px">
        محصولات مناسبت  ** @ViewBag.monasebat **

    </h1>
    <ol class="breadcrumb">
        <li><a href="/Admin/Default/Index"><i class="fa fa-dashboard"></i> مدیریت</a></li>
        <li class="active"><a href="/Admin/Monasebats/Index">       مناسبت ها</a></li>
        <li class="active">محصولات مناسبت @ViewBag.monasebat </li>
    </ol>
</section>

<section class="content  " id="GroupProducts">

    <div class="row">
        <div class="col-xs-12">
            <div class="box box box-info">
                <div class="box-header">
                    <h3 class="box-title">   محصولات مناسبت @ViewBag.monasebat</h3>

                    <div class="box-tools">
                        @using (Html.BeginForm("Index", "MonasebatProducts", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            <div class="input-group input-group-sm" style="width: 150px;">

                                <input type="text" name="search" class="form-control pull-right" placeholder="جستجو">

                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>

                            </div>
                        }
                    </div>

                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <tbody>
                            <tr>
                                <th>شماره</th>
                                <th> مناسبت</th>
                                <th>محصول</th>
                            </tr>
                            @foreach (var item in Model)
                            {
                                <tr role="row" class="table-striped table-hover">
                                    <td class="sorting_1">@counter</td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Monasebats.MonasebatTitle)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Products.CodeKala)
                                    </td>



                                    <td>
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-info btn-flat dropdown-toggle" data-toggle="dropdown">عملیات</button>
                                            <button type="button" class="btn btn-info btn-flat dropdown-toggle" data-toggle="dropdown">
                                                <span class="caret"></span>
                                                <span class="sr-only">Toggle Dropdown</span>
                                            </button>
                                            <ul class="dropdown-menu" role="menu">
                                               
                                                <li>@Html.ActionLink("ویرایش", "Edit", new { id = item.Id }, new { @class = "btn btn-block btn-danger btn-flat", @style = "color:white" })</li>
                                                <li>@Html.ActionLink("جزئیات", "Details", new { id = item.Id }, new { @class = "btn btn-block btn-info btn-flat", @style = "color:white" })</li>
                                                <li>
                                                    @Html.ActionLink("حذف", "Delete", new { id = item.Id }, new { @class = "btn btn-block btn-warning btn-flat", @style = "color:white" })

                                                </li>

                                            </ul>
                                        </div>

                                    </td>

                                </tr>
                                counter++;
                            }

                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>

</section>

SalinoMvc5/Areas/Admin/Views/Monasebats/Edit.cshtml
@model Salino.Models.Monasebat

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="content-header">
    <h1 style="margin-bottom:15px">
        مناسبت ها

    </h1>
    <ol class="breadcrumb">
        <li><a href="/Admin/Default/Index"><i class="fa fa-dashboard"></i> مدیریت</a></li>
        <li class="active"><a href="/Admin/Monasebats/Index">       مناسبت ها</a></li>
        <li class="active">ویرایش مناسبت @Model.MonasebatTitle</li>
    </ol>
</section>
<div class="box box-info container">


    @using (Html.BeginForm("Edit", "Monasebats", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
    

        <div class="form-horizontal">
            <h4>ویرایش مناسبت @Model.MonasebatTitle</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.MonasebatTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MonasebatTitle, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MonasebatTitle, "", new { @class = "text-danger" })
                </div>
            </div>

            <hr />

           

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button class="btn btn-social btn-success" type="submit">
                        <i class="fa fa-save"></i> ویرایش
                    </button>
                    <a class="btn btn-social btn-pinterest" href="/Admin/Monasebats/index">
                        <i class="fa fa-backward"></i> بازگشت
                    </a>
                </div>
            </div>
        </div>
    }


</div>

SalinoMvc5/Areas/Admin/Views/Monasebats/Index.cshtml
@model IEnumerable<Salino.Models.Monasebat>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    int counter = 1;
}

<section class="content-header">
        <h1>
            مناسبت ها
            <a class="btn btn-app" href="/Admin/Monasebats/Create">
                <i class="fa fa-hand-pointer-o"></i> مناسبت جدید
            </a>
            <a class="btn btn-app" href="/Admin/Monasebats/Index">
                <i class="fa fa-repeat"></i> به روزرسانی
            </a>
        </h1>
        <ol class="breadcrumb">
            <li><a href="/Admin/Default/Index"><i class="fa fa-dashboard"></i> مدیریت</a></li>
            <li class="active"><a href="/Admin/Monasebats/Index">     مناسبت ها</a></li>
        </ol>
    </section>

    <section class="content  " id="GroupProducts">

        <div class="row">
            <div class="col-xs-12">
                <div class="box box box-info">
                    <div class="box-header">
                        <h3 class="box-title"> مناسبت ها</h3>

                        <div class="box-tools">
                            @using (Html.BeginForm("Index", "Monasebats", FormMethod.Post, new { enctype = "multipart/form-data" }))
                            {
                                <div class="input-group input-group-sm" style="width: 150px;">

                                    <input type="text" name="search" class="form-control pull-right" placeholder="جستجو">

                                    <div class="input-group-btn">
                                        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                    </div>

                                </div>
                            }
                        </div>

                    </div>
                 
                    <div class="box-body table-responsive no-padding">
                        <table class="table table-hover">
                            <tbody>
                                <tr>
                                    <th>شماره</th>
                                    <th>عنوان مناسبت</th>

                                </tr>
                                @foreach (var item in Model)
                                {
                                    <tr role="row" class="table-striped table-hover">
                                        <td class="sorting_1">@counter</td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.MonasebatTitle)
                                        </td>



                                        <td>
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-info btn-flat dropdown-toggle" data-toggle="dropdown">عملیات</button>
                                                <button type="button" class="btn btn-info btn-flat dropdown-toggle" data-toggle="dropdown">
                                                    <span class="caret"></span>
                                                    <span class="sr-only">Toggle Dropdown</span>
                                                </button>
                                                <ul class="dropdown-menu" role="menu">
                                                    <li>
                                                        @Html.ActionLink("محصولات", "DetailsProducts", new { id = item.Id }, new { @class = "btn btn-block btn-primary btn-flat", @style = "color:white" })

                                                    </li>
                                                    <li>@Html.ActionLink("ویرایش", "Edit", new { id = item.Id }, new { @class = "btn btn-block btn-danger btn-flat", @style = "color:white" })</li>
                                                    <li>@Html.ActionLink("جزئیات", "Details", new { id = item.Id }, new { @class = "btn btn-block btn-info btn-flat", @style = "color:white" })</li>
                                                    <li>
                                                        @Html.ActionLink("حذف", "Delete", new { id = item.Id }, new { @class = "btn btn-block btn-warning btn-flat", @style = "color:white" })

                                                    </li>

                                                </ul>
                                            </div>

                                        </td>

                                    </tr>
                                    counter++;
                                }

                            </tbody>
                        </table>
                    </div>
                 
                </div>
        
            </div>
        </div>



    </section>


@*<div ng-app="Module">

    <section class="content-header">
        <h1>
            مناسبت ها
            <a class="btn btn-app" href="AddMonasebat">
                <i class="fa fa-hand-pointer-o"></i> مناسبت جدید
            </a>
            <a class="btn btn-app" href="ShowMonasebats">
                <i class="fa fa-repeat"></i> به روزرسانی
            </a>
        </h1>
        <ol class="breadcrumb">
            <li><a href="/Admin/Default/Index"><i class="fa fa-dashboard"></i> مدیریت</a></li>
            <li class="active"><a href="/Admin/Monasebats/Index">     مناسبت ها</a></li>
        </ol>
    </section>


    <div ng-view></div>
</div>
@section scripts{

    <script src="~/Angular/Scripts/angular.js"></script>
    <script src="~/Angular/Scripts/angular-route.min.js"></script>
    <script src="~/Angular/MyScript/Module.js"></script>
    <script src="~/Angular/MyScript/Service.js"></script>
    <script src="~/Angular/MyScript/AngularControllers/GetAllMonasebatsController.js"></script>
    <script src="~/Angular/MyScript/AngularControllers/AddMonasebatController.js"></script>*@

SalinoMvc5/Areas/Admin/Views/Monasebats/_ShowMonasebats.cshtml
<section class="content  " id="GroupProducts">

    <div class="row">
        <div class="col-xs-12">
            <div class="box box box-info">
                <div class="box-header">
                    <h3 class="box-title"> مناسبت ها</h3>

                    <div class="box-tools">
                        @using (Html.BeginForm("Index", "Monasebats", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            <div class="input-group input-group-sm" style="width: 150px;">

                                <input type="text" name="search" class="form-control pull-right" placeholder="جستجو">

                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>

                            </div>
                        }
                    </div>

                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <tbody>
                            <tr>
                                <th>شماره</th>
                                <th>عنوان مناسبت</th>

                            </tr>
                        
                                <tr role="row" class="table-striped table-hover"ng-repeat="m in Monasebats">
                                 
                                    <td>
                                        {{m.MonasebatTitle}}
                                    </td>



                                    <td>
                                      

                                    </td>

                                </tr>
                           
                          

                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>



</section>